//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public int id { get; set; }
        public string name { get; set; }
        public string roll_number { get; set; }
        public string @class { get; set; }
        public string section { get; set; }
        public string gender { get; set; }
        public string parent { get; set; }
    }
}
